create table if not exists public.sync_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  device_id uuid null,
  direction text not null check (direction in ('PUSH','PULL')),
  status text not null check (status in ('SUCCESS','PARTIAL','FAILED','CONFLICT')),
  mutation_count integer not null default 0 check (mutation_count >= 0),
  synced_count integer not null default 0 check (synced_count >= 0),
  conflict_count integer not null default 0 check (conflict_count >= 0),
  failed_count integer not null default 0 check (failed_count >= 0),
  cursor_from bigint null,
  cursor_to bigint null,
  duration_ms integer not null default 0 check (duration_ms >= 0),
  error_code text null,
  created_at timestamptz not null default now()
);

create index if not exists sync_events_user_created_idx on public.sync_events(user_id, created_at desc);
create index if not exists sync_events_device_created_idx on public.sync_events(device_id, created_at desc) where device_id is not null;

alter table public.sync_events enable row level security;

drop policy if exists sync_events_read_own on public.sync_events;
create policy sync_events_read_own on public.sync_events for select to authenticated using (user_id = (select auth.uid()));

revoke insert, update, delete on public.sync_events from anon, authenticated;
grant select on public.sync_events to authenticated;
